name: prometheus-ovs-exporter
version: 1.0.2
base: core18
grade: stable
summary: Prometheus OpenVswitch Exporter
description: |
  Exporter that exposes information gathered from OpenVswitch for use by the Prometheus monitoring system
confinement: strict
architectures:
  - build-on: arm64
parts:
  ovs-exporter:
    plugin: go
    go-channel: 1.14/stable
    source: https://github.com/greenpau/ovs_exporter.git
    source-tag: v1.0.2
    build-packages:
      - gcc
      - golang-go
    override-build: |
      GIT_COMMIT=$(git describe --dirty --always)
      GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD -- | head -1)
      BUILD_USER=snapcraft
      BUILD_DATE=$(date +"%Y-%m-%d")
      BINARY=ovs-exporter
      VERBOSE=-v
      PROJECT=github.com/greenpau/ovs_exporter
      PKG_DIR=pkg/ovs_exporter
      mkdir -p bin/
      rm -rf ./bin/*
      CGO_ENABLED=0 go build -o ./bin/${BINARY} \
      -ldflags="-w -s \
      -X github.com/prometheus/common/version.Version=$SNAPCRAFT_PROJECT_VERSION \
      -X github.com/prometheus/common/version.Revision=$GIT_COMMIT \
      -X github.com/prometheus/common/version.Branch=$GIT_BRANCH \
      -X github.com/prometheus/common/version.BuildUser=$BUILD_USER \
      -X github.com/prometheus/common/version.BuildDate=$BUILD_DATE \
      -X ${PROJECT}/${PKG_DIR}.appName=$BINARY \
      -X ${PROJECT}/${PKG_DIR}.appVersion=$SNAPCRAFT_PROJECT_VERSION \
      -X ${PROJECT}/${PKG_DIR}.gitBranch=$GIT_BRANCH \
      -X ${PROJECT}/${PKG_DIR}.gitCommit=$GIT_COMMIT \
      -X ${PROJECT}/${PKG_DIR}.buildUser=$BUILD_USER \
      -X ${PROJECT}/${PKG_DIR}.buildDate=$BUILD_DATE" \
      -gcflags="all=-trimpath=../src" \
      -asmflags="all=-trimpath ../src" \
      ./cmd/ovs_exporter/*.go
    override-prime: |
      snapcraftctl prime
      install -D $SNAPCRAFT_PART_SRC/../build/bin/ovs-exporter bin/ovs-exporter

  scripts:
    plugin: dump
    source: src
    organize:
      ovs-exporter-wrapper: bin/ovs-exporter.wrapper
      hooks/configure: meta/hooks/configure
apps:
  ovs-exporter:
    command: 'bin/ovs-exporter.wrapper'
    plugs:
      - network-bind
      - openvswitch
      - log-observe
      - system-observe
      - network-observe
      - netlink-audit
      - kernel-module-observe
    daemon: simple
hooks:
  configure:
    plugs: [network, network-bind]
